version: "3.9"
services:
  db:
    container_name: db-container
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: country_codes
    ports:
      - "3306:3306"
    networks:
      - backend-db
  backend:
    container_name: app-container
    build: .
    #image: backend-climaapp
    ports:
      - "9090:8080"
    restart: always
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/country_codes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend-db
networks:
 backend-db: