version: "3.9"
services:
  mysqldb:
    container_name: db-container
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: country_codes
    ports:
      - "3306:3306"
  my-app:
    depends_on:
      - mysqldb
    container_name: app-container
    build: .
    ports:
      - "9090:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/country_codes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root